name: Waka Readme

on:
  # for manual workflow trigger
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-readme:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master # this action name
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_TITLE: true # optional
          SECTION_NAME: waka # optional
          BLOCKS: -> # optional
          CODE_LANG: rust # optional
          TIME_RANGE: all_time # optional
          LANG_COUNT: 30 # optional
          SHOW_TIME: true # optional
          SHOW_TOTAL: true # optional
          SHOW_MASKED_TIME: false # optional
          STOP_AT_OTHER: false # optional
          IGNORED_LANGUAGES: |
            Other
            JSON
            Markdown
            XML
            YAML
            Text
            CSV
            TOML
            tmux
            INI
            Bash
            Shell
            "Git Config"
            Zsh
            Batchfile
            TSConfig
            ERB
            go.mod
            Textmate
            "ActionScript 3"
            gitignore
            vim
            Scheme
            D
            PowerShell
            Ezhil
            TSQL
